### ISSUE TITLE
Exclude files in specific directory

### ISSUE THREAD

**Issue by tyfoo1603** [DigitalKatalis/test_cov_console#23]
Hi,

I encounter some issues when running the coverage in multiple modules.

Here are my folder structure:

> Root
> |--assets
> |--coverage
> |--ios
> -------.symlinks
> ----------------- plugins
> |--lib
> |--modules
> |--test

When I run following command:
`flutter pub run test_cov_console -m -p==90 `

It returned 
```
Unhandled exception:
FileSystemException: Cannot open file, path = 'ios.symlinkspluginsclevertap_plugin/coverage/lcov.info' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
```
I had tried few approach to exlcude ios folder, but no luck solving this.
`flutter pub run test_cov_console -m -exclude=ios `
`flutter pub run test_cov_console -m -exclude='./ios' `
`flutter pub run test_cov_console -m -exclude='ios/*' `
`flutter pub run test_cov_console -m -exclude='ios/**' `

Appreciate if anyone can help on this issue. Thanks in advance!

**Comment by dk-imudita** [comment]
Hello,

From the error code, the program is trying to open 'ios.symlinkspluginsclevertap_plugin/coverage/lcov.info' file, however somehow it cannot be open due to some reasons (e.g. security access, etc).
So please make sure, when run it your login id has enough access to all related files (e.g. lcov.info, *.dart, *test.dart) etc.

**Please be noted:** the flow of this program would do the followings with '-m' (Report from multiple lcov.info files):
1. get all lcov.info files from current root directory and all sub-directories.
2. for each lcov.info file found from step 1, it will do:
- read lcov.info file **<== your case error is in this step**
- get list of files with coverage from lcov.info **<== option '--exclude' will do here**, so it would not solve your issue.
- etc.

Hope it would help you.

Thanks ..

**Comment by dk-imudita** [comment]
closed.
